const people = [
  {
    id: 1,
    first_name: "Elsa",
    last_name: "Pickhaver",
    email: "epickhaver0@theglobeandmail.com",
    gender: "Female",
    ip_address: "167.229.82.172",
    title: "Honorable",
    job_title: "Nuclear Power Engineer",
    race: "Menominee",
    company: "Nicolas, Kihn and Crist",
    age: 25,
  },

  {
    id: 2,
    first_name: "Clarance",
    last_name: "Vidineev",
    email: "cvidineev1@sitemeter.com",
    gender: "Male",
    ip_address: "118.25.7.56",
    title: "Mrs",
    job_title: "Analyst Programmer",
    race: "Seminole",
    company: "Cremin LLC",
    age: 28,
  },

  {
    id: 3,
    first_name: "Sondra",
    last_name: "Cossey",
    email: "scossey2@mapy.cz",
    gender: "Female",
    ip_address: "162.65.167.45",
    title: "Mr",
    job_title: "Associate Professor",
    race: "Uruguayan",
    company: "Lemke-Hartmann",
    age: 31,
  },

  {
    id: 4,
    first_name: "Ashly",
    last_name: "Kellough",
    email: "akellough3@nytimes.com",
    gender: "Female",
    ip_address: "29.157.132.185",
    title: "Ms",
    job_title: "Database Administrator I",
    race: "Puerto Rican",
    company: "Denesik Group",
    age: 42,
  },

  {
    id: 5,
    first_name: "Tiffanie",
    last_name: "Buncom",
    email: "tbuncom4@cafepress.com",
    gender: "Female",
    ip_address: "191.244.130.85",
    title: "Rev",
    job_title: "Recruiting Manager",
    race: "South American",
    company: "Macejkovic Group",
    age: 51,
  },

  {
    id: 6,
    first_name: "Nadean",
    last_name: "Fillis",
    email: "nfillis5@nature.com",
    gender: "Female",
    ip_address: "191.238.169.127",
    title: "Honorable",
    job_title: "Civil Engineer",
    race: "Honduran",
    company: "Senger Inc",
    age: 45,
  },

  {
    id: 7,
    first_name: "Roderich",
    last_name: "Marmion",
    email: "rmarmion6@sogou.com",
    gender: "Male",
    ip_address: "69.209.31.37",
    title: "Ms",
    job_title: "Research Nurse",
    race: "Cheyenne",
    company: "Green and Sons",
    age: 25,
  },

  {
    id: 8,
    first_name: "Free",
    last_name: "Sturgis",
    email: "fsturgis7@vinaora.com",
    gender: "Male",
    ip_address: "224.43.14.166",
    title: "Honorable",
    job_title: "VP Marketing",
    race: "Sri Lankan",
    company: "Cremin and Sons",
    age: 48,
  },

  {
    id: 9,
    first_name: "Raquel",
    last_name: "Lembke",
    email: "rlembke8@unc.edu",
    gender: "Female",
    ip_address: "150.108.236.231",
    title: "Rev",
    job_title: "Paralegal",
    race: "Navajo",
    company: "Goodwin Group",
    age: 50,
  },

  {
    id: 10,
    first_name: "Adah",
    last_name: "Cristofvao",
    email: "acristofvao9@dion.ne.jp",
    gender: "Female",
    ip_address: "38.66.189.140",
    title: "Mr",
    job_title: "Health Coach IV",
    race: "Korean",
    company: "Sipes-Bernier",
    age: 54,
  },
];
